-- Drop and recreate Cards table

DROP TABLE IF EXISTS cards CASCADE;
CREATE TABLE cards (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  sport VARCHAR(255) NOT NULL,
  player_name VARCHAR(255) NOT NULL,
  brand VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL,
  is_sold BOOLEAN NOT NULL DEFAULT FALSE,
  description TEXT
)
